### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Eve00000** [VoidRatio/TouchMixxx#2]
Hi, I discovered this by accident, I was making a TouchOSC screen to control Stems  in Mixxx, searching for a script hint google showed me your project.
Congratulations, realy nice.
Are you still working on it?
Maybe you should add it to the Mixxx controller mappings, there are new DJ's that can't already buy an expensive controller but want to play with their tablet(s) to try DJ-ing
Kind regards

**Comment by VoidRatio** [comment]
Hi, Eve00000, I'm not actively maintaining this project any more, but I am glad you found it useful.
